export interface Theme {
  name: string;
  url: string;
  image: string;
}

// Keep this order aligned with the legacy themes catalog.
export const themes = [
  { name: "Aetheria", url: "https://github.com/JJDizz1L/aetheria", image: "/assets/themes/aetheria.webp" },
  { name: "Amberbyte", url: "https://github.com/tahfizhabib/omarchy-amberbyte-theme", image: "/assets/themes/amberbyte.webp" },
  { name: "Arc Blueberry", url: "https://github.com/vale-c/omarchy-arc-blueberry", image: "/assets/themes/arc-blueberry.webp" },
  { name: "Archwave", url: "https://github.com/davidguttman/archwave", image: "/assets/themes/archwave.webp" },
  { name: "Ash", url: "https://github.com/bjarneo/omarchy-ash-theme", image: "/assets/themes/ash.webp" },
  { name: "Artzen", url: "https://github.com/tahfizhabib/omarchy-artzen-theme", image: "/assets/themes/artzen.webp" },
  { name: "Aura", url: "https://github.com/bjarneo/omarchy-aura-theme", image: "/assets/themes/aura.webp" },
  { name: "All Hallow's Eve", url: "https://github.com/guilhermetk/omarchy-all-hallows-eve-theme", image: "/assets/themes/all-hallow-s-eve.webp" },
  { name: "Atelier", url: "https://github.com/atif-1402/omarchy-atelier-theme", image: "/assets/themes/atelier.webp" },
  { name: "Ayaka", url: "https://github.com/abhijeet-swami/omarchy-ayaka-theme", image: "/assets/themes/ayaka.webp" },
  { name: "Azure Glow", url: "https://github.com/Hydradevx/omarchy-azure-glow-theme", image: "/assets/themes/azure-glow.webp" },
  { name: "Batman", url: "https://github.com/OldJobobo/omarchy-batman-theme", image: "/assets/themes/batman.webp" },
  { name: "Batou", url: "https://github.com/HANCORE-linux/omarchy-batou-theme", image: "/assets/themes/batou.webp" },
  { name: "Bauhaus", url: "https://github.com/somerocketeer/omarchy-bauhaus-theme", image: "/assets/themes/bauhaus.webp" },
  { name: "Biscuit de Mar Dark", url: "https://github.com/OldJobobo/omarchy-biscuit-de-mar-dark-theme", image: "/assets/themes/biscuit-de-mar-dark.webp" },
  { name: "Black Arch", url: "https://github.com/ankur311sudo/black_arch", image: "/assets/themes/black-arch.webp" },
  { name: "Black Gold", url: "https://github.com/HANCORE-linux/omarchy-blackgold-theme", image: "/assets/themes/black-gold.webp" },
  { name: "Black Turq", url: "https://github.com/HANCORE-linux/omarchy-blackturq-theme", image: "/assets/themes/black-turq.webp" },
  { name: "bluedotrb", url: "https://github.com/dotsilva/omarchy-bluedotrb-theme", image: "/assets/themes/bluedotrb.webp" },
  { name: "Blue Ridge Dark", url: "https://github.com/hipsterusername/omarchy-blueridge-dark-theme", image: "/assets/themes/blue-ridge-dark.webp" },
  { name: "Castle on a Lake", url: "https://github.com/shmall03/omarchy-castle-on-a-lake-theme", image: "/assets/themes/castle-on-a-lake.webp" },
  { name: "Catppuccin Mocha Dark", url: "https://github.com/Luquatic/omarchy-catppuccin-dark", image: "/assets/themes/catppuccin-mocha-dark.webp" },
  { name: "Citrus Cynapse", url: "https://github.com/Grey-007/citrus-cynapse", image: "/assets/themes/citrus-cynapse.webp" },
  { name: "City-783", url: "https://github.com/OldJobobo/omarchy-city-783-theme", image: "/assets/themes/city-783.webp" },
  { name: "Cobalt2", url: "https://github.com/hoblin/omarchy-cobalt2-theme", image: "/assets/themes/cobalt2.webp" },
  { name: "Commit", url: "https://github.com/c0ze/omarchy-commit-theme", image: "/assets/themes/commit.webp" },
  { name: "CpUnk", url: "https://github.com/stannorbvb-cmd/cpunk", image: "/assets/themes/cpunk.webp" },
  { name: "Crimson Gold", url: "https://github.com/knappkevin/omarchy-crimson-gold-theme", image: "/assets/themes/crimson-gold.webp" },
  { name: "Darcula", url: "https://github.com/noahljungberg/omarchy-darcula-theme", image: "/assets/themes/darcula.webp" },
  { name: "Demon", url: "https://github.com/HANCORE-linux/omarchy-demon-theme", image: "/assets/themes/demon.webp" },
  { name: "Dotrb", url: "https://github.com/dotsilva/omarchy-dotrb-theme", image: "/assets/themes/dotrb.webp" },
  { name: "Dos Moos", url: "https://github.com/HANCORE-linux/omarchy-dos-moos-theme", image: "/assets/themes/dos-moos.webp" },
  { name: "Drac", url: "https://github.com/ShehabShaef/omarchy-drac-theme", image: "/assets/themes/drac.webp" },
  { name: "Dracula", url: "https://github.com/catlee/omarchy-dracula-theme", image: "/assets/themes/dracula.webp" },
  { name: "Eldritch", url: "https://github.com/eldritch-theme/omarchy", image: "/assets/themes/eldritch.webp" },
  { name: "Event Horizon", url: "https://github.com/OldJobobo/omarchy-event-horizon-theme", image: "/assets/themes/event-horizon.webp" },
  { name: "Evergarden", url: "https://github.com/celsobenedetti/omarchy-evergarden", image: "/assets/themes/evergarden.webp" },
  { name: "Felix", url: "https://github.com/TyRichards/omarchy-felix-theme", image: "/assets/themes/felix.webp" },
  { name: "Fireside", url: "https://github.com/bjarneo/omarchy-fireside-theme", image: "/assets/themes/fireside.webp" },
  { name: "Flat Dracula", url: "https://github.com/OldJobobo/omarchy-flat-dracula-theme", image: "/assets/themes/flat-dracula.webp" },
  { name: "Flexoki Dark", url: "https://github.com/euandeas/omarchy-flexoki-dark-theme", image: "/assets/themes/flexoki-dark.webp" },
  { name: "Forest Green", url: "https://github.com/abhijeet-swami/omarchy-forest-green-theme", image: "/assets/themes/forest-green.webp" },
  { name: "Frost", url: "https://github.com/bjarneo/omarchy-frost-theme", image: "/assets/themes/frost.webp" },
  { name: "fuchsblau", url: "https://github.com/fuchsblau/omarchy-fuchsblau-theme", image: "/assets/themes/fuchsblau.webp" },
  { name: "Futurism", url: "https://github.com/bjarneo/omarchy-futurism-theme", image: "/assets/themes/futurism.webp" },
  { name: "Futurist", url: "https://github.com/benwillems/omarchy-futurist-theme", image: "/assets/themes/futurist.webp" },
  { name: "Gand", url: "https://github.com/c0ze/omarchy-gand-theme", image: "/assets/themes/gand.webp" },
  { name: "Ghost Pastel", url: "https://github.com/row-huh/omarchy-ghost-pastel-theme", image: "/assets/themes/ghost-pastel.webp" },
  { name: "Gold Rush", url: "https://github.com/tahayvr/omarchy-gold-rush-theme", image: "/assets/themes/gold-rush.webp" },
  { name: "Golden Brown", url: "https://github.com/atif-1402/omarchy-golden-brown-theme", image: "/assets/themes/golden-brown.webp" },
  { name: "The Greek", url: "https://github.com/HANCORE-linux/omarchy-thegreek-theme", image: "/assets/themes/the-greek.webp" },
  { name: "Greek Noir", url: "https://github.com/HANCORE-linux/omarchy-greek-noir-theme", image: "/assets/themes/greek-noir.webp" },
  { name: "Green Garden", url: "https://github.com/kalk-ak/omarchy-green-garden-theme", image: "/assets/themes/green-garden.webp" },
  { name: "Gruvbox Material", url: "https://github.com/curbol/omarchy-gruvbox-material", image: "/assets/themes/gruvbox-material.webp" },
  { name: "Gruvu", url: "https://github.com/ankur311sudo/gruvu", image: "/assets/themes/gruvu.webp" },
  { name: "Harbor", url: "https://github.com/HANCORE-linux/omarchy-harbor-theme", image: "/assets/themes/harbor.webp" },
  { name: "Harbor Dark", url: "https://github.com/HANCORE-linux/omarchy-harbordark-theme", image: "/assets/themes/harbor-dark.webp" },
  { name: "Hinterlands", url: "https://github.com/OldJobobo/omarchy-hinterlands-theme", image: "/assets/themes/hinterlands.webp" },
  { name: "Infernium", url: "https://github.com/RiO7MAKK3R/omarchy-infernium-dark-theme", image: "/assets/themes/infernium.webp" },
  { name: "Inky Pinky", url: "https://github.com/HANCORE-linux/omarchy-inkypinky-theme", image: "/assets/themes/inky-pinky.webp" },
  { name: "Japan Night", url: "https://github.com/devgtv/omarchy-japan-night-theme", image: "/assets/themes/japan-night.webp" },
  { name: "Lamplight", url: "https://github.com/thisisgm/omarchy-lamplight-theme", image: "/assets/themes/lamplight.webp" },
  { name: "Map Quest", url: "https://github.com/ItsABigIgloo/omarchy-mapquest-theme", image: "/assets/themes/map-quest.webp" },
  { name: "Mars", url: "https://github.com/steve-lohmeyer/omarchy-mars-theme", image: "/assets/themes/mars.webp" },
  { name: "Matrix", url: "https://github.com/BVisagie/omarchy-matrix-theme", image: "/assets/themes/matrix.webp" },
  { name: "Mechanoonna", url: "https://github.com/HANCORE-linux/omarchy-mechanoonna-theme", image: "/assets/themes/mechanoonna.webp" },
  { name: "Miasma", url: "https://github.com/OldJobobo/omarchy-miasma-theme", image: "/assets/themes/miasma.webp" },
  { name: "Midnight", url: "https://github.com/JaxonWright/omarchy-midnight-theme", image: "/assets/themes/midnight.webp" },
  { name: "Milky Matcha", url: "https://github.com/hipsterusername/omarchy-milkmatcha-light-theme", image: "/assets/themes/milky-matcha.webp" },
  { name: "Mini Jcw", url: "https://github.com/davydotcom/omarchy-mini-jcw-theme", image: "/assets/themes/mini-jcw.webp" },
  { name: "Monochrome", url: "https://github.com/Swarnim114/omarchy-monochrome-theme", image: "/assets/themes/monochrome.webp" },
  { name: "Monokai", url: "https://github.com/bjarneo/omarchy-monokai-theme", image: "/assets/themes/monokai.webp" },
  { name: "Moodpeak", url: "https://github.com/HANCORE-linux/omarchy-moodpeak-theme", image: "/assets/themes/moodpeak.webp" },
  { name: "Nagai Poolside", url: "https://github.com/somerocketeer/omarchy-nagai-poolside-theme", image: "/assets/themes/nagai-poolside.webp" },
  { name: "Naysayer", url: "https://github.com/brianblakely/omarchy-naysayer-theme", image: "/assets/themes/naysayer.webp" },
  { name: "Neo Sploosh", url: "https://github.com/monoooki/omarchy-neo-sploosh-theme", image: "/assets/themes/neo-sploosh.webp" },
  { name: "Neovoid", url: "https://github.com/RiO7MAKK3R/omarchy-neovoid-theme", image: "/assets/themes/neovoid.webp" },
  { name: "Neptune Blue", url: "https://github.com/davydotcom/omarchy-neptune-blue-theme", image: "/assets/themes/neptune-blue.webp" },
  { name: "NES", url: "https://github.com/bjarneo/omarchy-nes-theme", image: "/assets/themes/nes.webp" },
  { name: "Noir", url: "https://github.com/tahadx/omarchy-noir-theme", image: "/assets/themes/noir.webp" },
  { name: "Noir Dawn", url: "https://github.com/tahadx/omarchy-noir-dawn-theme", image: "/assets/themes/noir-dawn.webp" },
  { name: "Omacarchy", url: "https://github.com/RiO7MAKK3R/omarchy-omacarchy-theme", image: "/assets/themes/omacarchy.webp" },
  { name: "OmaLED", url: "https://github.com/brianblakely/omarchy-omaled-theme", image: "/assets/themes/omaled.webp" },
  { name: "One Dark Pro", url: "https://github.com/sc0ttman/omarchy-one-dark-pro-theme", image: "/assets/themes/one-dark-pro.webp" },
  { name: "Oxo Carbon", url: "https://github.com/HANCORE-linux/omarchy-oxocarbon-theme", image: "/assets/themes/oxo-carbon.webp" },
  { name: "Pagan", url: "https://github.com/c0ze/omarchy-pagan-theme", image: "/assets/themes/pagan.webp" },
  { name: "Pandora", url: "https://github.com/imbypass/omarchy-pandora-theme", image: "/assets/themes/pandora.webp" },
  { name: "Periphery", url: "https://github.com/r-bart/omarchy-periphery-theme", image: "/assets/themes/periphery.webp" },
  { name: "Pina", url: "https://github.com/bjarneo/omarchy-pina-theme", image: "/assets/themes/pina.webp" },
  { name: "Pink Blood", url: "https://github.com/ITSZXY/pink-blood-omarchy-theme", image: "/assets/themes/pink-blood.webp" },
  { name: "Pulsar", url: "https://github.com/bjarneo/omarchy-pulsar-theme", image: "/assets/themes/pulsar.webp" },
  { name: "Purple Moon", url: "https://github.com/Grey-007/purple-moon", image: "/assets/themes/purple-moon.webp" },
  { name: "Purplewave", url: "https://github.com/dotsilva/omarchy-purplewave-theme", image: "/assets/themes/purplewave.webp" },
  { name: "Rainy Night", url: "https://github.com/atif-1402/omarchy-rainynight-theme", image: "/assets/themes/rainy-night.webp" },
  { name: "Red Monarch", url: "https://github.com/kamatealif/omarchy-red-monarch-theme", image: "/assets/themes/red-monarch.webp" },
  { name: "Retro 82", url: "https://github.com/OldJobobo/omarchy-retro-82-theme", image: "/assets/themes/retro-82.webp" },
  { name: "RetroPC", url: "https://github.com/rondilley/omarchy-retropc-theme", image: "/assets/themes/retropc.webp" },
  { name: "Ristretto Light", url: "https://github.com/brokkoli71/omarchy-ristretto-light-theme", image: "/assets/themes/ristretto-light.webp" },
  { name: "RobZee84", url: "https://github.com/robzolkos/omarchy-robzee84-theme", image: "/assets/themes/robzee84.webp" },
  { name: "Rose Pine Dark", url: "https://github.com/guilhermetk/omarchy-rose-pine-dark", image: "/assets/themes/rose-pine-dark.webp" },
  { name: "Rose Pine Moon", url: "https://github.com/Memnoc/omarchy-rose-pine-moon-theme", image: "/assets/themes/rose-pine-moon.webp" },
  { name: "Rose of Dune", url: "https://github.com/HANCORE-linux/omarchy-roseofdune-theme", image: "/assets/themes/rose-of-dune.webp" },
  { name: "Ryu", url: "https://github.com/HANCORE-linux/omarchy-ryu-theme", image: "/assets/themes/ryu.webp" },
  { name: "Sakura", url: "https://github.com/bjarneo/omarchy-sakura-theme", image: "/assets/themes/sakura.webp" },
  { name: "Sakura Mochi", url: "https://github.com/OldJobobo/omarchy-sakura-mochi-theme", image: "/assets/themes/sakura-mochi.webp" },
  { name: "Saga", url: "https://github.com/HANCORE-linux/omarchy-saga-theme", image: "/assets/themes/saga.webp" },
  { name: "Sapphire", url: "https://github.com/HANCORE-linux/omarchy-sapphire-theme", image: "/assets/themes/sapphire.webp" },
  { name: "Shades of Jade", url: "https://github.com/HANCORE-linux/omarchy-shadesofjade-theme", image: "/assets/themes/shades-of-jade.webp" },
  { name: "Space Monkey", url: "https://github.com/TyRichards/omarchy-space-monkey-theme/", image: "/assets/themes/space-monkey.webp" },
  { name: "Snow", url: "https://github.com/bjarneo/omarchy-snow-theme", image: "/assets/themes/snow.webp" },
  { name: "Snow Black", url: "https://github.com/ankur311sudo/snow_black", image: "/assets/themes/snow-black.webp" },
  { name: "Solarized", url: "https://github.com/Gazler/omarchy-solarized-theme", image: "/assets/themes/solarized.webp" },
  { name: "Solarized Light", url: "https://github.com/dfrico/omarchy-solarized-light-theme", image: "/assets/themes/solarized-light.webp" },
  { name: "Solarized Osaka", url: "https://github.com/motorsss/omarchy-solarizedosaka-theme", image: "/assets/themes/solarized-osaka.webp" },
  { name: "Starsend", url: "https://github.com/r-bart/omarchy-starsend-theme", image: "/assets/themes/starsend.webp" },
  { name: "Sunset", url: "https://github.com/rondilley/omarchy-sunset-theme", image: "/assets/themes/sunset.webp" },
  { name: "Sunset Drive", url: "https://github.com/tahayvr/omarchy-sunset-drive-theme", image: "/assets/themes/sunset-drive.webp" },
  { name: "Super Game Bro", url: "https://github.com/TyRichards/omarchy-super-game-bro-theme", image: "/assets/themes/super-game-bro.webp" },
  { name: "Synthwave '84", url: "https://github.com/omacom-io/omarchy-synthwave84-theme/", image: "/assets/themes/synthwave-84.webp" },
  { name: "Temerald", url: "https://github.com/Ahmad-Mtr/omarchy-temerald-theme", image: "/assets/themes/temerald.webp" },
  { name: "Terminus", url: "https://github.com/r-bart/omarchy-terminus-theme", image: "/assets/themes/terminus.webp" },
  { name: "Tokyo Night OLED", url: "https://github.com/Justin-De-Sio/omarchy-tokyoled-theme", image: "/assets/themes/tokyo-night-oled.webp" },
  { name: "Tycho", url: "https://github.com/leonardobetti/omarchy-tycho", image: "/assets/themes/tycho.webp" },
  { name: "Waffle Cat", url: "https://github.com/OldJobobo/omarchy-waffle-cat-theme", image: "/assets/themes/waffle-cat.webp" },
  { name: "Waveform Dark", url: "https://github.com/hipsterusername/omarchy-waveform-dark-theme", image: "/assets/themes/waveform-dark.webp" },
  { name: "White Gold", url: "https://github.com/HANCORE-linux/omarchy-whitegold-theme", image: "/assets/themes/white-gold.webp" },
  { name: "Windows Dark Mode", url: "https://github.com/oldjobobo/omarchy-windows-dark-mode-theme", image: "/assets/themes/windows-dark-mode.webp" },
  { name: "Winslow", url: "https://github.com/chipkoziara/omarchy-winslow-theme", image: "/assets/themes/winslow.webp" },
  { name: "Van Gogh", url: "https://github.com/Nirmal314/omarchy-van-gogh-theme", image: "/assets/themes/van-gogh.webp" },
  { name: "Vault", url: "https://github.com/r-bart/omarchy-vault-theme", image: "/assets/themes/vault.webp" },
  { name: "Velvet Night", url: "https://github.com/HANCORE-linux/omarchy-velvetnight-theme", image: "/assets/themes/velvet-night.webp" },
  { name: "Venice from Above", url: "https://github.com/mattbbia/venice-from-above-omarchy", image: "/assets/themes/venice-from-above.webp" },
  { name: "Vesper", url: "https://github.com/thmoee/omarchy-vesper-theme", image: "/assets/themes/vesper.webp" },
  { name: "VHS 80", url: "https://github.com/tahayvr/omarchy-vhs80-theme", image: "/assets/themes/vhs-80.webp" },
  { name: "Void", url: "https://github.com/vyrx-dev/omarchy-void-theme", image: "/assets/themes/void.webp" },
] satisfies Theme[];
